### ISSUE TITLE
Usage!

### ISSUE THREAD

**Issue by Dershowitz011** [akemin-dayo/KarenPrefs#1]
How to use make install-to-theos? It says rule not found. Even in my project. Help please?

**Comment by Dershowitz011** [comment]
Solved. But when I run `make install-to-theos` , it says
In file included from KarenPrefsBounceBackSwitchCell.m:1:
./KarenPrefsBounceBackSwitchCell.h:1:9: fatal error: 'Preferences/PSSwitchTableCell.h' file not found
#import <Preferences/PSSwitchTableCell.h>

:disappointed: 

`

**Comment by Gh0stByte** [comment]
Chang it to 
`#import <Preferences/PSSwitchTableCell.h>`

**Comment by akemin-dayo** [comment]
@Gh0stByte That's already being used, his problem can't be fixed with that.

@Dershowitz011 You're missing some crucial headers KarenPrefs needs. I'll try to merge them into the official Theos headers repo.

For now, put these files in `$THEOS/include/Preferences/`

https://github.com/coolstar/theosheaders/blob/master/Preferences/PSEditableTableCell.h

https://github.com/coolstar/theosheaders/blob/master/Preferences/PSSwitchTableCell.h

Should fix your issues.

**Comment by Dershowitz011** [comment]
It compiled alright @angelXwind , but then
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/PrivateFrameworks'
ld: library not found for -lprefs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 :(

**Comment by akemin-dayo** [comment]
`iPhoneOS9.3.sdk` does not include the PrivateFrameworks folder due to changes by Apple.

Download this `iPhoneOS9.2.sdk`: https://jbdevs.org/sdks/dl/iPhoneOS9.2.sdk.tbz2

And copy `iPhoneOS9.2.sdk/System/Library/PrivateFrameworks` to your `iPhoneOS9.3.sdk`.

**Comment by Dershowitz011** [comment]
Done. but now 
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/PrivateFrameworks'
has disappeared.
But 
ld: library not found for -lprefs
clang: error: linker command failed with exit code 1 (use -v to see invocation)

still remains. @angelXwind

**Comment by akemin-dayo** [comment]
You need `libprefs.dylib`.

You can get mine from here: https://developer.angelxwind.net/iOS/libprefs.dylib

Or `scp` it directly from your own device (it will be at `/usr/lib/libprefs.dylib` on your iOS device).

Drop that file in `$THEOS/lib/` and you should be good.

**Comment by Dershowitz011** [comment]
Hey @angelXwind where do I paste it in my theos folder? include? Or should it be in the iphonesdk private frameworks folder?

**Comment by akemin-dayo** [comment]
@Dershowitz011 It should be in `$THEOS/lib/` as written above.

All headers (`*.h`) you want to use with Theos should go in `$THEOS/include/`, and all libraries (`*.dylib`) you want to use with Theos should go in `$THEOS/lib/`. They should never go anywhere else.

**Comment by Dershowitz011** [comment]
RIght! Give me 5 mins. I've been trying to get this right since 10 days. And @angelXwind how'd the people on reddit who have commented on your post got it right in the first time?

**Comment by akemin-dayo** [comment]
@Dershowitz011 Well, the first error you ran into (`iPhoneOS9.3.sdk` not having private frameworks) is a well-known issue that actually is not specific to KarenPrefs, and would have happened to any developer writing any tweaks that linked against private frameworks. We actually have an issue thread for this over at the [Theos repo](https://github.com/theos/theos/issues/146).

And as for your missing `libprefs.dylib`, I also think most developers already have `libprefs.dylib` in their libraries directory, since most preference bundles used in tweaks link against it (it's part of PreferenceLoader).

Same thing goes for your missing Preferences headers — though I'm working on getting those included in the Theos headers repository so people can have them by default.

**Comment by Dershowitz011** [comment]
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

_Banging my head on the wall_

**Comment by akemin-dayo** [comment]
@Dershowitz011 Which symbols aren't being found?

Might not do anything, but try `make clean` just to be sure nothing weird happened.

**Comment by Dershowitz011** [comment]
Done!! Thank you so much @angelXwind ! Thanks a bunch! 

I like an idiot had changed the libkarenprefs_LDFLAGS to libkarenprefs_CFFLAGS. Changed it back to libkarenprefs_LDFLAGS! Works now. Library merged. wooohooo..

**Comment by akemin-dayo** [comment]
Glad I could help.

(Just in case that wasn't a typo, `_CFFLAGS` isn't a thing — perhaps you meant `_CFLAGS`? Though I think that was just a typo ;P)

**Comment by Dershowitz011** [comment]
Yes it was a typo! I meant _CFLAGS! What on earth does _CFFLAGS mean? 😄 . Perhaps the next "make update-theos" will contain all the necessary files so that others shouldn't suffer so much to get stuff right? You can't keep helping everybody @angelXwind ?

**Comment by Dershowitz011** [comment]
Hey it's come up with a new error now:
cp: /opt/theos/lib/libkarenprefs.dylib: Permission denied
make: **\* [install-to-theos] Error 1

Help??

**Comment by Dershowitz011** [comment]
Was able to solve this by using 
`sudo chown -R "$USER":admin /opt/theos`

FIXED!

**Comment by akemin-dayo** [comment]
The headers have already been added to the Theos vendor include dir.

libprefs is also technically there, but not on the `master` branch yet. (It exists in TBD form as opposed to dylib)

So this won't be an issue for future developers.
